using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using UnityEngine.SceneManagement;
using Unity.VisualScripting;

public class GameManager : MonoBehaviour
{

    public GameObject playerPrefab;
    public GameObject enemyOnePrefab;
    public GameObject enemyTwoPrefab;
    public GameObject cloudPrefab;
    public GameObject powerupPrefab;
    public GameObject coinPrefab;
    public GameObject audioPlayer;

    // Audios
    public AudioClip powerupSound;
    public AudioClip powerdownSound;

    // Text
    public GameObject gameOverText;
    public GameObject restartText;
    public TextMeshProUGUI livesText;
    public TextMeshProUGUI scoreText;
    public TextMeshProUGUI powerupText;

    public float horizontalScreenSize;
    public float verticalScreenSize;
    public int score;
    public int cloudMove;
    private bool gameOver;

    // Start is called before the first frame update
    void Start()
    {
        horizontalScreenSize = 8.5f;
        verticalScreenSize = 3.5f;
        score = 0;
        cloudMove = 1;
        gameOver = false;
        AddScore(0);
        // Excluding this line because player is already present before startup.
        //Instantiate(playerPrefab, transform.position, Quaternion.identity);
        
        CreateSky();
        
        InvokeRepeating("CreateEnemy", 2, 3);
        InvokeRepeating("CreateEnemy2", 1, 3);
        InvokeRepeating("CreatePowerup", 1, 4);
        InvokeRepeating("CreateCoin", 1, 4);

        /*StartCoroutine(SpawnCoin());
        StartCoroutine(SpawnPowerup());*/
        powerupText.text = "No powerups yet!";
    }

    // Update is called once per frame
    void Update()
    {
        if (gameOver && Input.GetKeyDown(KeyCode.R))
        {
            SceneManager.LoadScene(SceneManager.GetActiveScene().name);
        }
    }

    void CreateEnemy()
    {
        Instantiate(enemyOnePrefab, new Vector3(Random.Range(-horizontalScreenSize, horizontalScreenSize) * 0.9f, verticalScreenSize, 0), Quaternion.Euler(180, 0, 0));
    }

    void CreateEnemy2()
    {
        Instantiate(enemyTwoPrefab, new Vector3(Random.Range(-1.3f, horizontalScreenSize), verticalScreenSize, 0), Quaternion.Euler(180, 0, 0));
    }

    void CreatePowerup()
    {
        Instantiate(powerupPrefab, new Vector3(Random.Range(-horizontalScreenSize * 0.8f, horizontalScreenSize * 0.8f), verticalScreenSize, 0), Quaternion.identity);
    }

    void CreateCoin()
    {
        Instantiate(coinPrefab, new Vector3(Random.Range(-horizontalScreenSize * 0.8f, horizontalScreenSize * 0.8f), verticalScreenSize, 0), Quaternion.identity);
    }

    void CreateSky()
    {
        for (int i = 0; i < 30; i++)
        {
            Instantiate(cloudPrefab, new Vector3(Random.Range(-horizontalScreenSize - 2.5f, horizontalScreenSize + 2.5f), Random.Range(-verticalScreenSize, verticalScreenSize), 0), Quaternion.identity);
        }

    }

    public void ManagePowerupText(int powerupType)
    {
        switch (powerupType)
        {
            case 1:
                powerupText.text = "Speed!";
                break;
            case 2:
                powerupText.text = "Double Weapon!";
                break;
            case 3:
                powerupText.text = "Triple Weapon!";
                break;
            case 4:
                powerupText.text = "Shield!";
                break;
            default:
                powerupText.text = "No powerups yet!";
                break;
        }
    }
    /*
    IEnumerator SpawnPowerup()
    {
        float spawnTime = Random.Range(3, 5);
        yield return new WaitForSeconds(spawnTime);
        CreatePowerup();
        StartCoroutine(SpawnPowerup());
    }

    IEnumerator SpawnCoin()
    {
        float spawnTime = Random.Range(3, 5);
        yield return new WaitForSeconds(spawnTime);
        CreateCoin();
        StartCoroutine(SpawnCoin());
    }
    */

    public void PlaySound(int whichSound)
    {
        switch (whichSound)
        {
            case 1:
                audioPlayer.GetComponent<AudioSource>().PlayOneShot(powerupSound);
                break;
            case 2:
                audioPlayer.GetComponent<AudioSource>().PlayOneShot(powerdownSound);
                break;
        }
    }

    public void AddScore(int pointsAdded)
    {
        score += pointsAdded;
        Debug.Log("Score: " + score);
        scoreText.text = "Score: " + score;
    }

    public void ChangeLivesText(int currentLives)
    {
        livesText.text = "Lives: " + currentLives;
        Debug.Log("Lives: " + currentLives);
    }

    public void GameOver()
    {
        gameOverText.SetActive(true);
        restartText.SetActive(true);
        gameOver = true;
        CancelInvoke();
        cloudMove = 0;
    }
}